config/routes.rb
Rails.application.routes.draw do
  get 'gyms/index'
  get 'gyms/show'
  get 'gyms/new'
  get 'gyms/edit'
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/new'
  get 'restaurants/edit'
  get 'my_restaurants', to: "pages#my_restaurants"
  get 'my_gyms', to: "pages#my_gyms"
  get 'user_dashboard', to: "pages#user_dashboard", as: :user_dashboard
  get 'owner_dashboard', to: "pages#owner_dashboard", as: :ownerdashboard
  get 'favorite', to: "pages#favorite", as: :favorite
  get 'dietary_requirements', to: "pages#dietary_requirements"
  post 'dietary_requirements', to: "pages#create_dietary"
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    post 'favorite', to: 'restaurants#favorite', as: :fav_res
    post 'unfavorite', to: 'restaurants#unfavorite', as: :unfav_res
    resources :dishes
    resources :restaurant_bookings, only: [ :new, :create, :index, :destroy, :show]
    resources :restaurant_reviews, only: :create
  end

  resources :restaurant_bookings, only: [:update, :edit, :destroy, :show]

  resources :gyms do
    resources :gym_classes, only: [:new, :create]
    post 'favorite', to: 'gyms#favorite', as: :fav_gym
    post 'unfavorite', to: 'gyms#unfavorite', as: :unfav_gym
    resources :gym_reviews, only: :create
  end

  resources :class_bookings, only: [:update, :edit, :destroy, :show]

  resources :gym_classes do
    resources :class_bookings, only: [:new, :create, :destroy, :show]
  end

  resources :chatrooms, only: :index

  resources :chatrooms, only: :show do
  resources :messages, only: :create
end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<% if user_signed_in? == false %>
<div class="footer footer-visitor">
  <div class="footer-links d-none">
    <a href="https://www.instagram.com/fitmapp/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/pages/category/Health---Wellness-Website/Fitmapp-100254108127279/" target="_blank"><i class="fab fa-facebook-f"></i></a>
    <a href="https://www.pinterest.co.uk/fitmapp/" target="_blank"><i class="fab fa-pinterest-p"></i></a>
  </div>
  <div class="footer-copyright">
    © fitmapp
  </div>
</div>
<% else %>
  <div class="footer bg-transparent">
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" href="<%= image_path 'fav_marker_1.png' %>" />

app/views/shared/_nav_bottom.html.erb
<% if user_signed_in? %>
<nav class="nav nav-pills nav-justified d-flex justify-content-around bottom-nav fixed-bottom pt-1">
  <!-- <a class="nav-item nav-link" href="#" > Restaurants </a> -->
    <%= link_to restaurants_path do %>
      <i class="nav-item nav-link fas fa-utensils"></i>
    <% end %>
    <%= link_to gyms_path do %>
      <i class="nav-item nav-link fas fa-dumbbell"></i>
    <% end %>
    <%= link_to chatrooms_path do %>
      <i class="nav-item nav-link fas fa-comment"></i>
    <% end %>
    <% if current_user.owner %>
      <%= link_to ownerdashboard_path do %>
        <i class="nav-item nav-link fas fa-user-circle"></i>
      <% end %>
    <% else %>
      <%= link_to user_dashboard_path do %>
        <i class="nav-item nav-link fas fa-user-circle"></i>
      <% end %>
    <% end %>
</nav>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-xs navbar-light navbar-lewagon sticky-top pt-1">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_colour_zoom.png" %>
    <% end %>


  <div class="" id="navbarSupportedContent">
      <% if user_signed_in? %>
        <% if current_user&.owner? %>
          <div class="d-flex">
            <%= link_to "NEW RESTAURANT", new_restaurant_path, class: "nav-link px-2" %>
            <%= link_to "NEW GYM", new_gym_path, class: "nav-link px-0" %>
          </div>
        <% else %>
          <div class="search-navbar">
            <%= form_tag restaurants_path, class: "navbar-wagon-search navbar-version rounded p-0", method: :get do %>
            <%= text_field_tag :address,
                params[:address],
                class: "navbar-wagon-search-input navbar-version nav-rounded",
                placeholder: "Search Location" %>

              <%= button_tag( :class => "btn navbar-wagon-search-btn navbar-version d-flex") do %>
                <i class="fa fa-search"> </i>
              <% end %>
            <% end %>
          </div>
          <% end %>
      <% else %>
        <button class="btn-login rounded">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link rounded", style: "color: white" %>
        </button>
      <% end %>
  </div>
</div>