config/routes.rb
Rails.application.routes.draw do
  get 'gyms/index'
  get 'gyms/show'
  get 'gyms/new'
  get 'gyms/edit'
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/new'
  get 'restaurants/edit'
  get 'my_restaurants', to: "pages#my_restaurants"
  get 'my_gyms', to: "pages#my_gyms"
  get 'user_dashboard', to: "pages#user_dashboard", as: :user_dashboard
  get 'owner_dashboard', to: "pages#owner_dashboard", as: :ownerdashboard
  get 'favorite', to: "pages#favorite", as: :favorite
  get 'dietary_requirements', to: "pages#dietary_requirements"
  post 'dietary_requirements', to: "pages#create_dietary"
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    post 'favorite', to: 'restaurants#favorite', as: :fav_res
    post 'unfavorite', to: 'restaurants#unfavorite', as: :unfav_res
    resources :dishes
    resources :restaurant_bookings, only: [ :new, :create, :index, :destroy, :show]
    resources :restaurant_reviews, only: :create
  end

  resources :restaurant_bookings, only: [:update, :edit, :destroy, :show]

  resources :gyms do
    resources :gym_classes, only: [:new, :create]
    post 'favorite', to: 'gyms#favorite', as: :fav_gym
    post 'unfavorite', to: 'gyms#unfavorite', as: :unfav_gym
    resources :gym_reviews, only: :create
  end

  resources :class_bookings, only: [:update, :edit, :destroy, :show]

  resources :gym_classes do
    resources :class_bookings, only: [:new, :create, :destroy, :show]
  end

  resources :chatrooms, only: :index

  resources :chatrooms, only: :show do
  resources :messages, only: :create
end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :dishes, dependent: :destroy
  has_many :restaurant_bookings, dependent: :destroy
  has_many :restaurant_reviews, dependent: :destroy

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  acts_as_favoritable
  acts_as_taggable_on :dietary

  include PgSearch::Model
    pg_search_scope :search_by_location,
      against: [ :address],
      using: {
        tsearch: { prefix: true }
      }

  DIETARY = ["Vegan", "Vegetarian", "Keto", "Paleo", "Pescatarian", "Gluten free", "Lactose-free", "Dairy-free"]

  def average_rating
    return 0 if self.restaurant_reviews.length == 0
    review_sum = 0
    review_count = self.restaurant_reviews.length
    self.restaurant_reviews.each do |review|
      review_sum += review.rating
     end
      return (review_sum / review_count)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :show]
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    if params[:address].present?
      @restaurants = policy_scope(Restaurant).search_by_location(params[:address])
    else
      @restaurants = policy_scope(Restaurant)
    end
    @restaurants = @restaurants.geocoded

    @markers = @restaurants.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { restaurant: restaurant }),
        image_url: helpers.asset_url('fork&knife3.png')
      }
    end

    if params["search"]
      @filter = params["search"]["dietary"].reject(&:empty?)
      @restaurants = @filter.empty? ? @restaurants : @restaurants.tagged_with(@filter, any: true)
    end
  end

  def show
    @markers = [{
      lat: @restaurant.latitude,
      lng: @restaurant.longitude,
      infoWindow: render_to_string(partial: "infowindow", locals: { restaurant: @restaurant }),
      image_url: helpers.asset_url('fork&knife3.png')
    }]
    @restaurant_booking = RestaurantBooking.new
    @restaurant_review = RestaurantReview.new
  end

  def new
    @restaurant = Restaurant.new
    authorize @restaurant
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.user = current_user
    if @restaurant.save
      redirect_to ownerdashboard_path
    else
      render :new
    end
    authorize @restaurant
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  def favorite
    @restaurant = Restaurant.find(params[:restaurant_id])
    authorize @restaurant
    current_user.favorite(@restaurant)
    redirect_to restaurant_path(@restaurant)
  end

  def unfavorite
    @restaurant = Restaurant.find(params[:restaurant_id])
    authorize @restaurant
    current_user.unfavorite(@restaurant)
    redirect_to restaurant_path(@restaurant)
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category, :photo, :dietary_list)
  end

  def set_restaurant
    @restaurant = Restaurant.geocoded
    @restaurant = Restaurant.find(params[:id])
    authorize @restaurant
  end

end

app/views/restaurants/_form_dish.html.erb
<%= simple_form_for @restaurant do |f| %>
<div class="row">
  <div class="col-6"><%= f.input :name %></div>
  <div class="col-6"><%= f.input :description %></div>
</div>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/restaurants/_form_restaurant.html.erb
<%= simple_form_for @restaurant do |f| %>
<div class="row">
  <div class="col-6"><%= f.input :name %></div>
  <div class="col-6"><%= f.input :address %></div>
</div>
<div class="row">
  <div class="col"><%= f.input :category %></div>
</div>
  <%= f.input :photo, as: :file %>
  <br>
  <div class="d-flex justify-content-center">
    <%= link_to "Back", ownerdashboard_path, class: "btn btn-secondary mr-2" %>
    <%= f.submit class: "btn btn-primary"%>
</div>
<% end %>

app/views/restaurants/_infowindow.html.erb
<div class="map-card">
  <h5 class="map-card-name"> <%= link_to restaurant.name, restaurant_path(restaurant)%> </h5>
  <p class="map-card-address"> <%= restaurant.address %> </p>
  <%= link_to "Directions", "https://www.google.com/maps/dir/?api=1&travelmode=walking&layer=traffic&destination=#{restaurant.latitude},#{restaurant.longitude}", class: "btn-small btn-primary p-2 rounded map-card-btn", target: :_blank%>
</div>

app/views/restaurants/edit.html.erb
<div class="container justify-content-center w-75 new-gym-container mt-5 mb-5 p-5 shadow">
    <h3 class="p-4 text-center">Update Restaurant</h3>

    <%= render "form_restaurant", restaurant: @restaurant %>
</div>
<br>
<br>

app/views/restaurants/index.html.erb
<div class="container pb-4 shadow rounded new-gym-container">
  <h1 class="text-center pt-4"> Nearby Restaurants </h1>
    <!-- Collapse button -->
        <p class="text-center m-3">
          <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            Filter
          </a>
        </p>
        <div class="collapse" id="collapseExample">
        <div class="card card-body filter-container mb-2 p-2 justify-content-center text-center">
            <%= simple_form_for :search, url: restaurants_path, method: "GET" do |f| %>
            <%= f.input :dietary, collection: Restaurant::DIETARY, as: :check_boxes, wrapper: :vertical_collection_inline %>
          <div class="d-flex justify-content-center">
            <%= f.submit "Search", class: "btn-secondary btn btn-sm" %>
          <% end %>
          </div>
        </div>
        </div>

  <div class="row">
    <% @restaurants.each do |restaurant| %>
      <div class="col-xs-12 col-md-6 col-lg-4 mb-3">
        <%= link_to restaurant_path(restaurant) do %>
          <div class="card-product rounded">
            <% if restaurant.photo.attached? %>
              <%= cl_image_tag restaurant.photo.key %>
            <% end %>
            <div class="card-product-infos w-100">
              <h2><%= restaurant.name %>
                <% if user_signed_in? %>
                  <% if restaurant.favorited_by?(current_user) %>
                    <i class="fas fa-heart fav-heart-index"></i>
                  <% end %>
                <% end %>
              </h2>
              <p><%= restaurant.category %></p>
              <p class="text-right">
                <% if restaurant.average_rating <= 0  %>
                  <%= image_tag "0star.png", alt: "0 stars", class: "star-rating" %>
                  <% elsif restaurant.average_rating <= 1 %>
                  <%= image_tag "1star.png", alt: "1 stars", class: "star-rating" %>
                  <% elsif restaurant.average_rating <= 2 %>
                  <%= image_tag "2star.png", alt: "2 stars", class: "star-rating" %>
                  <% elsif restaurant.average_rating <= 3 %>
                  <%= image_tag "3star.png", alt: "3 stars", class: "star-rating" %>
                  <% elsif restaurant.average_rating <= 4 %>
                  <%= image_tag "4star.png", alt: "4 stars", class: "star-rating" %>
                  <% else %>
                  <%= image_tag "5star.png", alt: "5 stars", class: "star-rating" %>
                <% end %>
              </p>
            </div>
          </div>
        <% end %>

      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
          <div class="modal-content">
            <img src="https://images.unsplash.com/photo-1565700549653-3ae074ab0d6d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" class="card-img-top" alt="...">
              <div class="rest-card-body">
                <h5 class="rest-card-title"><%= restaurant.name %></h5>
                <p class="rest-card-text"><%= restaurant.address %></p>
                <p class="rest-card-text"><%= restaurant.category %></p>
                <ul class="list-group list-group-flush">
                  <% restaurant.dishes.each do |dish| %>
                    <li class="list-group-item"><i class="fas fa-utensils"></i> - <strong> <%= dish.name %> </strong>- <%= dish.description %></li>
                  <% end %>
                </ul>
              </div>
              <div class="card-body">
                <%= link_to "Book #{restaurant.name} Now", "...", class: "btn btn-primary btn-sm" %>
                <%= link_to "Back to all Restaurants", restaurants_path, class: "btn btn-secondary btn-sm"  %>
              </div>
          </div>
        </div>
      </div>

      </div>
    <% end %>
  </div>

  <div id="map"
    style="width: 100%; height: 400px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/restaurants/new.html.erb
<div class="container justify-content-center w-75 new-gym-container mt-5 mb-1 p-4 shadow">
  <h2 class="p-4 text-center">New Restaurant</h2>

  <%= render "form_restaurant", restaurant: @restaurant %>
</div>

app/views/restaurants/show.html.erb
<div class="container my-3">
  <div class="rest-card bg-light rounded">

    <% if @restaurant.photo.attached? %>
      <%= cl_image_tag @restaurant.photo.key, class: "card-img-top rounded-top" %>
    <% end %>

    <div class="rest-card-body d-flex flex-column justify-content-center ">
      <% if user_signed_in? && !current_user.owner %>
        <span class="text-right">
          <% if @restaurant.favorited_by?(current_user) %>
            <%= link_to restaurant_unfav_res_path(@restaurant), method: :post, remote: true do  %>
              <i class="fas fa-heart fav-heart"></i>
            <% end %>
          <% else %>
            <%=  link_to restaurant_fav_res_path(@restaurant), method: :post, remote: true do %>
              <i class="far fa-heart fav-heart"></i>
            <% end %>
          <% end %>
        </span>
      <% end %>
      <h5 class="rest-card-title text-center"><%= @restaurant.name %></h5>
        <p class="text-center total_reviews">
          <%= link_to restaurant_path(@restaurant, anchor: "review") do  %>
              <% if @restaurant.average_rating <= 0  %>
              <%= image_tag "0star.png", alt: "alttext" %>
              <% elsif @restaurant.average_rating <= 1 %>
              <%= image_tag "1star.png", alt: "alttext" %>
              <% elsif @restaurant.average_rating <= 2 %>
              <%= image_tag "2star.png", alt: "alttext" %>
              <% elsif @restaurant.average_rating <= 3 %>
              <%= image_tag "3star.png", alt: "alttext" %>
              <% elsif @restaurant.average_rating <= 4 %>
              <%= image_tag "4star.png", alt: "alttext" %>
              <% else %>
              <%= image_tag "5star.png", alt: "alttext" %>
            <% end %>
            (<%= @restaurant.restaurant_reviews.count %>)
            <% end %> </p>
      <p class="rest-card-text text-center m-0"><%= @restaurant.address %></p>
      <p class="rest-card-text text-center">Type: <%= @restaurant.category %></p>
      <span class="badge badge-primary dietary-show"><%= @restaurant.dietary_list %> </span>
    </div>


      <div class="container">
        <div class="row">
          <% @restaurant.dishes.each do |dish| %>
            <div class="col-6 col-md-4 mb-4 card-container">
              <div class="card-flip shadow">
              <% if dish.photo.attached?  %>
                <div class="front", style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path dish.photo.key %>)">
                  <h5 class="text-center text-white m-2"><%= dish.name %>    </h5>
                </div>
              <% else %>
                <div class="front", style="background-image: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5))">
                  <h5 class="text-center text-white m-2"> <%= dish.name %> </h5>
                </div>
              <% end %>
              <div class="back p-4">
                <h6 class="pb-1 text-center"> <%= dish.name %> </h6>
                <p class="text-center"> <%= dish.description %> </p>
              </div>
        </div>
      </div>
      <% end %>

        </div>
    </div>

    <div class="card-body">
      <% if @restaurant.user != current_user %>
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#RestaurantBookingsModal">
          <%= "Book" %>
        </button>
      <% end %>

      <div class="modal fade" id="RestaurantBookingsModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content bg-light">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel"><strong>Book a Table</strong></h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <%= simple_form_for [@restaurant, @restaurant_booking] do |f| %>
              <div class="row">
                <div class="col-6"><%= f.input :date, html5: true %></div>
                <div class="col-6"><%= f.input :time, html5: true %></div>
              </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                  <%= f.button :submit, "Make Booking", { class: "trigger-btn btn-primary", "data-toggle": "#myModal" } %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>


      <% if @restaurant.user == current_user %>
        <%= link_to "Add dishes", new_restaurant_dish_path(@restaurant), class: "btn btn-primary btn-sm" %>
      <% end %>

      <!-- Button trigger modal -->
      <% if @restaurant.user == current_user %>
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModalCenter">
          Add new tags
        </button>
      <% end %>

      <!-- Modal -->
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content bg-light">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalCenterTitle"> Update tags </h5>
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                  <%= simple_form_for @restaurant do |f| %>
                  <%= f.input :dietary_list %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.button :submit, 'Save', class: "btn btn-primary" %>
              <% end %>
            </div>
           </div>
        </div>
      </div>

      <% if !current_user.owner %>
        <%= link_to "Get Directions", "https://www.google.com/maps/dir/?api=1&travelmode=walking&layer=traffic&destination=#{@restaurant.latitude},#{@restaurant.longitude}", class: "btn btn-primary", target: :_blank, class: "btn btn-primary btn-sm" %>
      <% end %>
      <%= link_to "Back", restaurants_path, class: "btn btn-secondary btn-sm"  %>

    </div>
    <div id="map"
      class="container"
      style="width: 100%; height: 300px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <div class="review_section">
      <div id="review_form">
        <%= simple_form_for([ @restaurant, @restaurant_review ], remote: true) do |f| %>
          <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
          <%= f.input :content, as: :text %>
          <%= f.button :submit, "Post Review", class: "btn btn-primary" %>
        <% end %>
      </div>

      <div id="restaurant_reviews">
        <% if @restaurant.restaurant_reviews.blank? %>
          Be the first to leave a review for <%= @restaurant.name %>
        <% else %>
          <% @restaurant.restaurant_reviews.reverse_order.each do |review| %>
          <div id="review">
            <div class="rating">
              <% if review.rating == 0 %>
                <%= image_tag "0star.png", alt: "alttext" %>
                <% elsif review.rating == 1 %>
                <%= image_tag "1star.png", alt: "alttext" %>
                <% elsif review.rating == 2 %>
                <%= image_tag "2star.png", alt: "alttext" %>
                <% elsif review.rating == 3 %>
                <%= image_tag "3star.png", alt: "alttext" %>
                <% elsif review.rating == 4 %>
                <%= image_tag "4star.png", alt: "alttext" %>
                <% else %>
                <%= image_tag "5star.png", alt: "alttext" %>
              <% end %>
              <br>
              <%= review.created_at.strftime("%b %Y") %>
            </div>
            <div class="content">
              '<%= review.content %>'
            </div>
          </div>
          <% end %>
        <% end %>
      </div>

    </div>
  </div>
</div>