config/routes.rb
Rails.application.routes.draw do
  get 'gyms/index'
  get 'gyms/show'
  get 'gyms/new'
  get 'gyms/edit'
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/new'
  get 'restaurants/edit'
  get 'my_restaurants', to: "pages#my_restaurants"
  get 'my_gyms', to: "pages#my_gyms"
  get 'user_dashboard', to: "pages#user_dashboard", as: :user_dashboard
  get 'owner_dashboard', to: "pages#owner_dashboard", as: :ownerdashboard
  get 'favorite', to: "pages#favorite", as: :favorite
  get 'dietary_requirements', to: "pages#dietary_requirements"
  post 'dietary_requirements', to: "pages#create_dietary"
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    post 'favorite', to: 'restaurants#favorite', as: :fav_res
    post 'unfavorite', to: 'restaurants#unfavorite', as: :unfav_res
    resources :dishes
    resources :restaurant_bookings, only: [ :new, :create, :index, :destroy, :show]
    resources :restaurant_reviews, only: :create
  end

  resources :restaurant_bookings, only: [:update, :edit, :destroy, :show]

  resources :gyms do
    resources :gym_classes, only: [:new, :create]
    post 'favorite', to: 'gyms#favorite', as: :fav_gym
    post 'unfavorite', to: 'gyms#unfavorite', as: :unfav_gym
    resources :gym_reviews, only: :create
  end

  resources :class_bookings, only: [:update, :edit, :destroy, :show]

  resources :gym_classes do
    resources :class_bookings, only: [:new, :create, :destroy, :show]
  end

  resources :chatrooms, only: :index

  resources :chatrooms, only: :show do
  resources :messages, only: :create
end
end

app/models/gym.rb
class Gym < ApplicationRecord

  belongs_to :user
  has_many :gym_classes, dependent: :destroy
  has_many :class_bookings, through: :gym_classes, dependent: :destroy
  has_many :gym_reviews, dependent: :destroy

  has_one_attached :photo

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  acts_as_favoritable

  acts_as_taggable_on :styles

  STYLE = ["Boxing", "Dance studio", "Yoga studio", "Pilates", "General"]

  def average_rating
    return 0 if self.gym_reviews.length == 0
    review_sum = 0
    review_count = self.gym_reviews.length
    self.gym_reviews.each do |review|
      review_sum += review.rating
     end
      return (review_sum / review_count)
  end

end

app/controllers/gyms_controller.rb
class GymsController < ApplicationController
  before_action :set_gym, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy, :show]

  def index
    @gyms = policy_scope(Gym)
    @gyms = Gym.geocoded
    @markers = @gyms.map do |gym|
      {
        lat: gym.latitude,
        lng: gym.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { gym: gym }),
        image_url: helpers.asset_url('logofinal_colour_marker.png')
      }
    end

    if params["search"]
      @filter = params["search"]["styles"].reject(&:empty?)
      @gyms = @filter.empty? ? @gyms : @gyms.tagged_with(@filter, any: true)
    end
  end

  def show
    @markers = [{
      lat: @gym.latitude,
      lng: @gym.longitude,
      infoWindow: render_to_string(partial: "infowindow", locals: { gym: @gym }),
      image_url: helpers.asset_url('logofinal_colour_marker.png')
    }]
    @class_booking = ClassBooking.new
    @gym_review = GymReview.new
  end

  def new
    @gym = Gym.new
    authorize @gym
  end

  def create
    @gym = Gym.new(gym_params)
    @gym.user = current_user
    if @gym.save
      redirect_to ownerdashboard_path
    else
      render :new
    end
    authorize @gym
  end

  def edit
  end

  def update
    if @gym.update(gym_params)
      redirect_to @gym
    else
      render :edit
    end
  end

  def destroy
    @gym.destroy
    redirect_to :index
  end

  def favorite
    @gym = Gym.find(params[:gym_id])
    authorize @gym
    current_user.favorite(@gym)
    redirect_to gym_path(@gym)
  end

  def unfavorite
    @gym = Gym.find(params[:gym_id])
    authorize @gym
    current_user.unfavorite(@gym)
    redirect_to gym_path(@gym)
  end

  private

  def gym_params
    params.require(:gym).permit(:name, :address, :category, :photo, :style_list)
  end

  def set_gym
    @gym = Gym.geocoded
    @gym = Gym.find(params[:id])
    authorize @gym
  end
end

app/views/gyms/_form_classes.html.erb
<%= simple_form_for @gym do |f| %>
<div class="row">
  <div class="col-6"><%= f.input :name %></div>
  <div class="col-6"><%= f.input :time %></div>
</div>
  <%= f.input :photo, as: :file %>
  <%= f.submit class: "btn btn-primary"%>
<% end %>

app/views/gyms/_form_gym.html.erb
<%= simple_form_for @gym do |f| %>
<div class="row">
  <div class="col-6"><%= f.input :name %></div>
  <div class="col-6"><%= f.input :address %></div>
</div>
<div class="row">
  <div class="col"><%= f.input :category %></div>
</div>
  <%= f.input :photo, as: :file %>
  <br>
  <div class="d-flex justify-content-center">
  <%= link_to "Back", ownerdashboard_path, class: "btn btn-secondary mr-2" %>
  <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/gyms/_infowindow.html.erb
<div class="map-card">
  <h5 class="map-card-name" style="color: #E4F2F6"> <%= link_to gym.name, gym_path(gym) %> </h5>
  <p class="map-card-address"> <%= gym.address %> </p>
  <%= link_to "Directions", "https://www.google.com/maps/dir/?api=1&travelmode=walking&layer=traffic&destination=#{gym.latitude},#{gym.longitude}", class: "btn-small btn-primary p-2 rounded map-card-btn", target: :_blank %>
</div>

app/views/gyms/edit.html.erb
<div class="container justify-content-center w-75 new-gym-container mt-5 mb-5 p-5 shadow">
  <h3 class="p-4 text-center">Update Gym</h3>

  <%= render "form_gym", gym: @gym %>

</div>
<br>
<br>

app/views/gyms/index.html.erb
<div class="container pb-4 shadow rounded new-gym-container">
  <h1 class="text-center pt-4"> Nearby Gyms </h1>
    <!-- Collapse button -->
        <p class="text-center m-3">
          <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
            Filter
          </a>
        </p>
        <div class="collapse" id="collapseExample">
        <div class="card card-body filter-container mb-2 p-2 justify-content-center text-center">
            <%= simple_form_for :search, url: gyms_path, method: "GET" do |f| %>
            <%= f.input :styles, label: "Style",  collection: Gym::STYLE, as: :check_boxes, wrapper: :vertical_collection_inline %>
          <div class="d-flex justify-content-center">
            <%= f.submit "Search", class: "btn btn-secondary btn-sm" %>
          <% end %>
          </div>
        </div>
        </div>

  <div class="row">
    <% @gyms.each do |gym| %>
    <div class="col-xs-12 col-md-6 col-lg-4 mb-3">
      <div class="card-product rounded">
         <% if gym.photo.attached? %>
              <%= cl_image_tag gym.photo.key %>
            <% end %>
          <div class="card-product-infos w-100">
            <%= link_to gym_path(gym) do %>
              <h2>
                <%= gym.name %>
                <% if user_signed_in? %>
                   <% if gym.favorited_by?(current_user) %>
                    <i class="fas fa-heart fav-heart-index"></i>
                  <% end %>
                <% end %>
              </h2>
              <p> <%= gym.category %> </p>
              <p class="text-right stars">
                <% if gym.average_rating <= 0  %>
                  <%= image_tag "0star.png", alt: "alttext", class: "star-rating" %>
                  <% elsif gym.average_rating <= 1 %>
                  <%= image_tag "1star.png", alt: "alttext", class: "star-rating" %>
                  <% elsif gym.average_rating <= 2 %>
                  <%= image_tag "2star.png", alt: "alttext", class: "star-rating" %>
                  <% elsif gym.average_rating <= 3 %>
                  <%= image_tag "3star.png", alt: "alttext", class: "star-rating" %>
                  <% elsif gym.average_rating <= 4 %>
                  <%= image_tag "4star.png", alt: "alttext", class: "star-rating" %>
                  <% else %>
                  <%= image_tag "5star.png", alt: "alttext", class: "star-rating" %>
                <% end %>
              </p>
            <% end %>
          </div>
      </div>
    </div>
    <% end %>
  </div>

  <div id="map"
     style="width: 100%; height: 400px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/gyms/new.html.erb
<div class="container justify-content-center w-75 new-gym-container mt-5 mb-1 p-4 shadow">
      <h2 class="p-4 text-center">New Gym</h2>

      <%= render "form_gym", gym: @gym %>
</div>

app/views/gyms/show.html.erb
<div class="container my-3">
  <div class="rest-card bg-light rounded">

    <% if @gym.photo.attached? %>
      <%= cl_image_tag @gym.photo.key, class: "card-img-top rounded-top" %>
    <% end %>

    <div class="rest-card-body d-flex flex-column justify-content-center">
      <% if user_signed_in? && !current_user.owner %>
        <span class="text-right">
          <% if @gym.favorited_by?(current_user) %>
            <%= link_to gym_unfav_gym_path(@gym), method: :post, remote: true do  %>
              <i class="fas fa-heart fav-heart"></i>
            <% end %>
          <% else %>
            <%=  link_to gym_fav_gym_path(@gym), method: :post, remote: true do %>
              <i class="far fa-heart fav-heart"></i>
            <% end %>
          <% end %>
        </span>
      <% end %>
        <h5 class="rest-card-title text-center"><%= @gym.name %></h5>
          <p class="text-center total_reviews">
            <%= link_to gym_path(@gym, anchor: "review") do  %>
              <% if @gym.average_rating <= 0  %>
                <%= image_tag "0star.png", alt: "alttext" %>
                <% elsif @gym.average_rating <= 1 %>
                <%= image_tag "1star.png", alt: "alttext" %>
                <% elsif @gym.average_rating <= 2 %>
                <%= image_tag "2star.png", alt: "alttext" %>
                <% elsif @gym.average_rating <= 3 %>
                <%= image_tag "3star.png", alt: "alttext" %>
                <% elsif @gym.average_rating <= 4 %>
                <%= image_tag "4star.png", alt: "alttext" %>
                <% else %>
                <%= image_tag "5star.png", alt: "alttext" %>
             <% end %>
            (<%= @gym.gym_reviews.count %>)
            <% end %>
          </p>
          <p class="rest-card-text text-center m-0"><%= @gym.address %></p>
          <p class="rest-card-text text-center">Type: <%= @gym.category %></p>
          <span class="badge badge-primary dietary-show mb-3"><%= @gym.style_list %> </span>

          <ul class="list-group list-group-flush rounded">
            <% @gym.gym_classes.each do |gymclass| %>
              <li class="list-group-item gym-classes">
                <span class="classes-list">
                <span class="class-details">
                  <i class="fas fa-dumbbell"></i> - <strong> <%= gymclass.name %> </strong>- <%= gymclass.time.strftime("%k:%M") %>
                </span>
              <!-- Book now -->
                <span class="book-buttons">
                  <% if @gym.user != current_user %>
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal<%= gymclass.id %> ">
                    <%= "Book" %>
                    </button>
                  <% else %>
                    <%= link_to "Edit", edit_gym_class_path(gymclass) %>
                  <% end %>
                </span>
                </span>

                <!-- Modal HTML -->
                <div id="myModal<%= gymclass.id %>" class="modal fade" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content bg-light">
                      <div class="modal-header">
                        <h5 class="modal-title"><strong>Pick a Date</strong></h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">
                        <%= simple_form_for [gymclass, ClassBooking.new] do |f| %>
                          <%= f.input :date, as: :date, html5: true, id:"date" %>
                        <div class="modal-footer">
                          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                          <%= f.button :submit, "Make Booking", class: "trigger-btn-gym btn-primary"%>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
      </div>

    <div class="card-body">

      <% if @gym.user == current_user %>
        <%= link_to "Add classes", new_gym_gym_class_path(@gym), class: "btn btn-primary btn-sm" %>
      <% end %>
      <!-- Button trigger TAGS modal -->
      <% if @gym.user == current_user %>
        <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#exampleModalCenter">
          Add new tags
        </button>
      <% end %>

      <!-- Tags Modal -->
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content bg-light">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalCenterTitle"> Update tags </h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
                  <%= simple_form_for @gym, method: "PATCH" do |f| %>
                  <%= f.input :style_list %>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
              <%= f.button :submit, 'Save', class: "btn btn-primary" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <% if !current_user.owner %>
        <%= link_to "Get Directions", "https://www.google.com/maps/dir/?api=1&travelmode=walking&layer=traffic&destination=#{@gym.latitude},#{@gym.longitude}", class: "btn btn-primary", target: :_blank, class: "btn btn-primary btn-sm" %>
      <% end %>
      <%= link_to "Back", gyms_path, class: "btn btn-secondary btn-sm"  %>
    </div>

    <div id="map"
      class="container"
      style="width: 100%; height: 300px;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

    <div class="review_section">

        <div id="review_form">
          <%= simple_form_for([ @gym, @gym_review ], remote: true) do |f| %>
            <%= f.input :rating, collection: (1..5).to_a, label: "Rate your experience" %>
            <%= f.input :content, as: :text %>
            <%= f.button :submit, "Post Review", class: "btn btn-primary" %>
          <% end %>
        </div>

        <div id="gym_reviews">
          <% if @gym.gym_reviews.blank? %>
            Be the first to leave a review for <%= @gym.name %>
          <% else %>
            <% @gym.gym_reviews.reverse_order.each do |review| %>
            <div id="review">
              <div class="rating">
                <% if review.rating == 0 %>
                  <%= image_tag "0star.png", alt: "alttext" %>
                  <% elsif review.rating == 1 %>
                  <%= image_tag "1star.png", alt: "alttext" %>
                  <% elsif review.rating == 2 %>
                  <%= image_tag "2star.png", alt: "alttext" %>
                  <% elsif review.rating == 3 %>
                  <%= image_tag "3star.png", alt: "alttext" %>
                  <% elsif review.rating == 4 %>
                  <%= image_tag "4star.png", alt: "alttext" %>
                  <% else %>
                  <%= image_tag "5star.png", alt: "alttext" %>
                <% end %>
                <br>
                <%= review.created_at.strftime("%b %Y") %>
              </div>
              <div class="content">
                '<%= review.content %>'
              </div>
            </div>
            <% end %>
          <% end %>
        </div>

    </div>
  </div>
</div>