config/routes.rb
Rails.application.routes.draw do
  get 'gyms/index'
  get 'gyms/show'
  get 'gyms/new'
  get 'gyms/edit'
  get 'restaurants/index'
  get 'restaurants/show'
  get 'restaurants/new'
  get 'restaurants/edit'
  get 'my_restaurants', to: "pages#my_restaurants"
  get 'my_gyms', to: "pages#my_gyms"
  get 'user_dashboard', to: "pages#user_dashboard", as: :user_dashboard
  get 'owner_dashboard', to: "pages#owner_dashboard", as: :ownerdashboard
  get 'favorite', to: "pages#favorite", as: :favorite
  get 'dietary_requirements', to: "pages#dietary_requirements"
  post 'dietary_requirements', to: "pages#create_dietary"
  devise_for :users, controllers: { registrations: "registrations" }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    post 'favorite', to: 'restaurants#favorite', as: :fav_res
    post 'unfavorite', to: 'restaurants#unfavorite', as: :unfav_res
    resources :dishes
    resources :restaurant_bookings, only: [ :new, :create, :index, :destroy, :show]
    resources :restaurant_reviews, only: :create
  end

  resources :restaurant_bookings, only: [:update, :edit, :destroy, :show]

  resources :gyms do
    resources :gym_classes, only: [:new, :create]
    post 'favorite', to: 'gyms#favorite', as: :fav_gym
    post 'unfavorite', to: 'gyms#unfavorite', as: :unfav_gym
    resources :gym_reviews, only: :create
  end

  resources :class_bookings, only: [:update, :edit, :destroy, :show]

  resources :gym_classes do
    resources :class_bookings, only: [:new, :create, :destroy, :show]
  end

  resources :chatrooms, only: :index

  resources :chatrooms, only: :show do
  resources :messages, only: :create
end
end

app/controllers/gym_classes_controller.rb
class GymClassesController < ApplicationController
  before_action :set_gym_class, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @gym_classes = policy_scope(GymClass)
    authorize @gym_classes
  end

  def show
  end

  def new
    @gym_class = GymClass.new
    @gym = Gym.find(params[:gym_id])
    authorize @gym_class
  end

  def create
    @gym_class = GymClass.new(gym_class_params)
    @gym = Gym.find(params[:gym_id])
    @gym_class.gym = @gym
    if @gym_class.save
      redirect_to gym_path(@gym)
    else
      render :new
    end
    authorize @gym_class
  end

  def edit
  end

  def update
    if @gym_class.update(gym_class_params)
      redirect_to @gym_class.gym
    else
      render :edit
    end
    authorize @gym_class
  end

  def destroy
    @gym_class.destroy
    redirect_to :index
  end

  private

  def gym_class_params
    params.require(:gym_class).permit(:name, :time, :photo, :gym_id)
  end

  def set_gym_class
    @gym_class = GymClass.find(params[:id])
    authorize @gym_class
  end
end

app/views/gym_classes/_form.html.erb
<%= simple_form_for [@gym, @gym_class] do |f| %>

  <%= f.input :name %>
  <%= f.input :time %>

  <%= f.input :photo, as: :file %>
  <br>
  <%= link_to "Back", ownerdashboard_path, class: "btn btn-secondary btn-sm" %>
  <%= f.submit class: "btn btn-primary btn-sm"%>
<% end %>

app/views/gym_classes/edit.html.erb
<div class="container justify-content-center w-75 my-5 new-gym-container">
      <h3 class="pt-4 text-center"> Update a Class</h3>

      <%= render "form", gym_class: @gym_class %>
<br>

</div>

app/views/gym_classes/new.html.erb
<div class="container justify-content-center w-50">
      <h1 class="pt-4 text-center">Add a new Gym Class</h1>

      <%= render "form", gym_class: @gym_class %>
  <br>
  <div class="back-to-gyms">
    <%= link_to "Back to my gyms", my_gyms_path, class: "btn btn-primary" %>
  </div>
</div>